Improve Invoke Release 4.2.0
ERROR: You are currently on branch "improve-workflow" instead of "master." You should only release from master or version branches, and this does not appear to be a version branch (must match \d+\.x\.x or \d+.\d+\.x).
Canceling release! workflow by suggesting a version to bump to.